info:
 app:
  name: Spring Boot 2 Axis 2
  java:
   version: 1.0.0
  type: Microservice API
server:
 address: 0.0.0.0 
 port: 50301 
management:
 endpoints:
  web:
   exposure:
    include: health,info